### ISSUE TITLE
About the codes and features

### ISSUE THREAD

**Issue by pipixin321** [joos2010kj/CLIP-TSA#1]
Nice works!
Have you considered releasing the Clip visual features extracted from UCF Crime and XD violence so that people can follow them better :)

**Comment by joos2010kj** [comment]
Hello!

The codes will be released around mid September and certainly before the conference meetup.  I apologize for the delay! I will close it once I have released it.

**Comment by joos2010kj** [comment]
Thanks for your patience.  The codes and the features are out! I will be closing this.

**Comment by pipixin321** [comment]
Thanks!
