### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by Xandra298** [joos2010kj/CLIP-TSA#2]
Would you share the features of the dataset you extracted with vit? Is there any reference code in the extraction process?

**Comment by joos2010kj** [comment]
<h4><a href="https://drive.google.com/file/d/1FvU8-qiVwiGF5BXAdM00-YhMZ7xt_vvy/view?usp=sharing">ShanghaiTech Campus Dataset</a></h4>
<h4><a href="https://drive.google.com/file/d/1bsVTixDxWdycDJhcTwqZV75suFrv76LB/view?usp=sharing">UCF-Crime Dataset</a></h4>
<h4><a href="https://drive.google.com/file/d/1HdN4_RcxvSp5scJ4k1PDgHHSZpEhGoZp/view?usp=sharing">XD-Violence Dataset</a></h4>

Here you go!

**Comment by Xandra298** [comment]
Thanks!
