### ISSUE TITLE
Feature-extraction and pre-processing code

### ISSUE THREAD

**Issue by yashika-git** [joos2010kj/CLIP-TSA#4]
Hi @joos2010kj, 

Is it possible for you to share the code/repositories used for feature extraction and pre-processing? Essentially, the code that could help in generating the features that are to be fed during training/evaluation.

Thank you

**Comment by xpwindells** [comment]
me too~~

**Comment by joos2010kj** [comment]
Hi,

Please refer to https://github.com/openai/CLIP?tab=readme-ov-file#usage for how to run the feature extraction.
