### ISSUE TITLE
about gpu？

### ISSUE THREAD

**Issue by GP0123** [joos2010kj/CLIP-TSA#6]
@joos2010kj  hello great work ！  I have encountered an issue with insufficient GPU memory and I have tried more gpus to train，such as CUDA_VISIBLE_DEVICES= 0，1，2 python. But it doesn't work,why?  Why does using multiple GPUs for training still encounter this problem？

**Comment by joos2010kj** [comment]
Hello, please refer to the FAQ in README for this.
