### ISSUE TITLE
Question: CLIP model for ShaghaiTech Dataset

### ISSUE THREAD

**Issue by eunjijeon11** [joos2010kj/CLIP-TSA#9]
Hello,

May I ask which CLIP model was used to process the ShanghaiTech dataset?

Thank you.

**Comment by joos2010kj** [comment]
Hi,

VIT-16 was used for this.

**Comment by eunjijeon11** [comment]
Thanks for the quick reply. Could you tell me which pretrained model you used? For example, did you use OpenAI's openai/clip-vit-base-patch16 model?

**Comment by joos2010kj** [comment]
Hello,

The following was used:

"ViT-B/16": "https://openaipublic.azureedge.net/clip/models/5806e77cd80f8b59890b7e101eabd078d9fb84e6937f9e85e4ecb61988df416f/ViT-B-16.pt"

**Comment by eunjijeon11** [comment]
Thanks!
